### ISSUE TITLE
Special Pickaxes Plugin Request

### ISSUE THREAD

**Issue by ToxicSp33dy** [PerceiveDev/PerceiveRequests#2]
## Suggested name
PrisonPicks

## Plugin category
Fun, Mechanics, Admin Tools

## Minecraft version(s)
1.8-1.12

## Description
I want a plugin that adds 3 new pickaxes, that are **Smelter's Pickaxe, Explosive Pickaxe, and Bountiful Pickaxe.** **The Smelter's Pickaxe** should smelt any ore and turn it into an ingot, and cobblestone should go to stone, and netherrack to nether bricks. **The Explosive Pickaxe** should do a 3x3x3 explosion, with the explosion particle and the explosion sound. **The Bountiful Pickaxe** should search a 3x3x3 area for the highest ore and give it to you. **All Pickaxes should be unbreakable and enchantable. Also this plugin should work with WorldGuard version 6.1.2 and above. Upon getting the Pickaxes they all should come enchanted with Unbreaking 1, and all lore's and names of the Pickaxes should be customizable in the Config.**
**Smelter's Pickaxe Lore**: A trusty pick that smelts what you mine!
**Explosive Pickaxe Lore**: Blast your way to the top!
**Bountiful Pickaxe Lore**: Drops the ores from others nearby!

## Commands
- /smelterspickaxe:  Gives yourself the Smelter's Pickaxe directly.
- /explosivepickaxe:  Gives yourself the Explosive Pickaxe directly.
- /bountifulpickaxe:  Gives yourself the Bountiful Pickaxe directly.
- /smelterspickaxe (playername):  Gives a player the Smelter's Pickaxe
- /explosivepickaxe (playername):  Gives a player the Explosive Pickaxe
- /bountifulpickaxe (playername):  Give a player the Bountiful Pickaxe

## Permissions
- PrisonPicks.admin: This Permission allow players to use the commands listed above.

## Deadline
3 Weeks.

**Comment by foxfirecodes** [comment]
I honestly completely forgot this repository even existed. The PerceiveDev team has been disbanded since around January of 2017. However, I may be able to do this request personally, please [join my Discord server](https://discord.io/rayzrdevofficial) if you would like to discuss this further.
